name: Build RE220

on:
  workflow_dispatch:
    inputs:
      KERNEL_REPO:
        description: 'KERNEL_REPO'
        required: false
        default: 'https://github.com/NCLnclNCL/re220v1_gplcode'

jobs:
  build_gpl:
    name: build ${{ matrix.gplv }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          docker pull NCLnclNCL/kernel-build:1.4
          docker tag NCLnclNCL/kernel-build:1.4 router_build

      - name: Prepare gpl code
        run: |
          git clone https://github.com/NCLnclNCL/re220v1_gplcode router
          cd router

      - name: Build GPL
        run: |
          set -o pipefail
            docker run --rm -v ./router:/router --user 1001 router_build bash -c "make SHELL=/bin/bash V=s -j$(nproc)"
