name: Generate JKS Keystore

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate JKS keystore
      run: |
        keytool -genkey -v \
          -keystore key.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias nclnclncl \
          -storepass a11223344 \
          -keypass a11223344 \
          -dname "CN=Example, OU=Dev, O=Example Corp, L=City, S=State, C=VN"

    - name: Encode keystore to base64
      run: |
        base64 key.jks > key.jks.b64

    - name: Show file size and hash
      run: |
        echo "Size:"
        stat --format="%s bytes" key.jks
        echo "SHA256:"
        sha256sum key.jks
    - name: Upload base64 keystore
      uses: actions/upload-artifact@v4
      with:
        name: keystore-b64
        path: key.jks.b64
    - name: Upload base64 keystore
      uses: actions/upload-artifact@v4
      with:
        name: keystore
        path: key.jks
