name: Build Python2.7.18 and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev zlib1g-dev libncurses5-dev \
            libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev \
            liblzma-dev tk-dev wget

    - name: Download and build Python 2.7.18
      run: |
        cd ${{ github.workspace }}
        wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        tar xzf Python-2.7.18.tgz
        cd Python-2.7.18
        ./configure --prefix=${{ github.workspace }}/python2
        make -j$(nproc)
        make install

    - name: Compress built Python2
      run: |
        cd ${{ github.workspace }}
        tar czf python2.7.18.tar.gz python2

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Python2.7.18 Build"
        tag_name: "python2.7.18"
        files: python2.7.18.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
