name: Build Python2.7.18 and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: sudo apt -y install gawk aria2 git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler
        

    - name: Download and build Python 2.7.18
      run: |
        cd ${{ github.workspace }}
        wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        tar xzf Python-2.7.18.tgz
        cd Python-2.7.18
        ./configure --prefix=${{ github.workspace }}/python2
        make -j$(nproc)
        make install

    - name: Compress built Python2
      run: |
        cd ${{ github.workspace }}
        tar czf python2.7.18.tar.gz python2

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Python2.7.18 Build"
        tag_name: "python2.7.18"
        files: python2.7.18.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
